<?php

$baseUrl = 'https://ceaindonesia.id';

return [
    'navigation' => [
        ['key' => 'beranda', 'label' => 'BERANDA', 'href' => '/', 'sourceHref' => $baseUrl.'/', 'description' => 'Halaman utama CEA Indonesia dan ringkasan aliansi.'],
        [
            'key' => 'profil',
            'label' => 'PROFIL',
            'href' => '/admin/profil',
            'publicHref' => '/profil',
            'publicHref' => '/profil/riwayat',
            'sourceHref' => $baseUrl.'/riwayat/',
            'description' => 'Kelola riwayat, mandat, struktur gerak, sumber daya, kontak, dan dokumen profil CEA.',
            'children' => [
                ['key' => 'riwayat', 'label' => 'Riwayat', 'href' => '/admin/profil/riwayat', 'publicHref' => '/profil/riwayat', 'sourceHref' => $baseUrl.'/riwayat/', 'description' => 'Latar pembentukan CEA dan kronologi rembug nasional.'],
                ['key' => 'mandat-visi-nilai', 'label' => 'Mandat, Visi, Nilai', 'href' => '/admin/profil/mandat-visi-nilai', 'publicHref' => '/profil/mandat-visi-nilai', 'sourceHref' => $baseUrl.'/mandat-visi-nilai-cea/', 'description' => 'Visi, mandat, tujuan, dan nilai-nilai gerakan CEA.'],
                ['key' => 'struktur-gerak', 'label' => 'Struktur Gerak', 'href' => '/admin/profil/struktur-gerak', 'publicHref' => '/profil/struktur-gerak', 'sourceHref' => $baseUrl.'/struktur-gerak-cea/', 'description' => 'Struktur jejaring, simpul regional, gugus tugas, dan kaukus isu.'],
                ['key' => 'sumber-daya', 'label' => 'Sumber Daya', 'href' => '/admin/profil/sumber-daya', 'publicHref' => '/profil/sumber-daya', 'sourceHref' => $baseUrl.'/tata-kelola-sumber-daya-cea/', 'description' => 'Tata kelola sumber daya, mobilisasi, distribusi, dan kontribusi aliansi.'],
                ['key' => 'kontak', 'label' => 'Kontak', 'href' => '/admin/profil/kontak', 'publicHref' => '/profil/kontak', 'sourceHref' => $baseUrl.'/kontak/', 'description' => 'Alamat sekretariat, kanal kontak, dan informasi penghubung publik.'],
                ['key' => 'unduh-profil-id', 'label' => 'Unduh Profil (ID)', 'href' => '/admin/profil/unduh-profil-id', 'publicHref' => '/profil/unduh-profil-id', 'sourceHref' => $baseUrl.'/unduh/profil-cea-versi-ponsel/', 'description' => 'Dokumen profil CEA versi bahasa Indonesia.'],
                ['key' => 'download-profile-en', 'label' => 'Download Profile (EN)', 'href' => '/admin/profil/download-profile-en', 'publicHref' => '/profil/download-profile-en', 'sourceHref' => $baseUrl.'/', 'description' => 'Dokumen profil CEA versi bahasa Inggris.'],
            ],
        ],
        [
            'key' => 'regio',
            'label' => 'REGIO',
            'href' => '/admin/regio',
            'publicHref' => '/regio',
            'sourceHref' => $baseUrl.'/',
            'description' => 'Kelola data simpul regional dan organisasi anggota CEA.',
            'children' => [
                ['key' => 'simpul', 'label' => 'Simpul', 'href' => '/admin/regio/simpul', 'publicHref' => '/regio/simpul', 'sourceHref' => $baseUrl.'/', 'description' => 'Peta simpul, focal point, wilayah kerja, dan status regional.'],
                ['key' => 'anggota', 'label' => 'Anggota', 'href' => '/admin/regio/anggota', 'publicHref' => '/regio/anggota', 'sourceHref' => $baseUrl.'/', 'description' => 'Direktori organisasi anggota, profil lembaga, dan relasi simpul.'],
            ],
        ],
        [
            'key' => 'siar',
            'label' => 'SIAR',
            'href' => '/admin/siar',
            'publicHref' => '/siar',
            'sourceHref' => $baseUrl.'/siar/',
            'description' => 'Kelola kanal publikasi CEA: kabar, rilis, prakarsa, refleksi, dan referensi.',
            'children' => [
                ['key' => 'kabar', 'label' => 'Kabar', 'href' => '/admin/siar/kabar', 'publicHref' => '/siar/kabar', 'sourceHref' => $baseUrl.'/siar/', 'description' => 'Artikel kabar terbaru dari kegiatan dan jejaring CEA.'],
                ['key' => 'rilis', 'label' => 'Rilis', 'href' => '/admin/siar/rilis', 'publicHref' => '/siar/rilis', 'sourceHref' => $baseUrl.'/siar/', 'description' => 'Rilis pers, pernyataan solidaritas, dan respons kelembagaan.'],
                ['key' => 'prakarsa', 'label' => 'Prakarsa', 'href' => '/admin/siar/prakarsa', 'publicHref' => '/siar/prakarsa', 'sourceHref' => $baseUrl.'/siar/', 'description' => 'Inisiatif, program, dan praktik kolaboratif dari simpul CEA.'],
                ['key' => 'refleksi', 'label' => 'Refleksi', 'href' => '/admin/siar/refleksi', 'publicHref' => '/siar/refleksi', 'sourceHref' => $baseUrl.'/siar/refleksi/', 'description' => 'Tulisan reflektif tentang ruang sipil, demokrasi, dan gerakan sosial.'],
                ['key' => 'referensi', 'label' => 'Referensi', 'href' => '/admin/siar/referensi', 'publicHref' => '/siar/referensi', 'sourceHref' => $baseUrl.'/siar/', 'description' => 'Bahan bacaan, dokumen pengetahuan, dan rujukan riset.'],
            ],
        ],
        [
            'key' => 'aksi',
            'label' => 'AKSI',
            'href' => '/admin/aksi',
            'publicHref' => '/aksi',
            'sourceHref' => $baseUrl.'/rencana-aksi-cea/',
            'description' => 'Kelola manifesto, kajian, gugus tugas, kaukus isu, dan diskursus publik CEA.',
            'children' => [
                ['key' => 'manifesto', 'label' => 'Manifesto', 'href' => '/admin/aksi/manifesto', 'publicHref' => '/aksi/manifesto', 'sourceHref' => $baseUrl.'/rencana-aksi-cea/', 'description' => 'Narasi dasar, posisi gerakan, dan arah aksi CEA.'],
                ['key' => 'kajian-strategis', 'label' => 'Kajian Strategis', 'href' => '/admin/aksi/kajian-strategis', 'publicHref' => '/aksi/kajian-strategis', 'sourceHref' => $baseUrl.'/siar/', 'description' => 'Kajian strategis dan analisis isu prioritas aliansi.'],
                ['key' => 'gugus-tugas', 'label' => 'Gugus Tugas', 'href' => '/admin/aksi/gugus-tugas', 'publicHref' => '/aksi/gugus-tugas', 'sourceHref' => $baseUrl.'/struktur-gerak-cea/', 'description' => 'Kelompok kerja civic space dan civic engagement.'],
                ['key' => 'kaukus-isu', 'label' => 'Kaukus Isu', 'href' => '/admin/aksi/kaukus-isu', 'publicHref' => '/aksi/kaukus-isu', 'sourceHref' => 'https://menjadiindonesia.org', 'description' => 'Kaukus tematik dan kanal isu lintas sektor.'],
                ['key' => 'diskursus', 'label' => 'Diskursus', 'href' => '/admin/aksi/diskursus', 'publicHref' => '/aksi/diskursus', 'sourceHref' => $baseUrl.'/', 'description' => 'Forum diskusi, percakapan publik, dan agenda pengetahuan.'],
            ],
        ],
        [
            'key' => 'koneksi',
            'label' => 'KONEKSI',
            'href' => '/admin/koneksi',
            'publicHref' => '/koneksi',
            'sourceHref' => $baseUrl.'/',
            'description' => 'Kelola koneksi ekosistem, platform kolaborasi, dan kanal mitra CEA.',
            'children' => [
                ['key' => 'lokadana', 'label' => 'Lokadana', 'href' => '/admin/koneksi/lokadana', 'publicHref' => '/koneksi/lokadana', 'sourceHref' => 'https://lokadana.lokadaya.id', 'description' => 'Platform hibah partisipatif dan mobilisasi sumber daya.'],
                ['key' => 'iwrf', 'label' => 'IWRF', 'href' => '/admin/koneksi/iwrf', 'publicHref' => '/koneksi/iwrf', 'sourceHref' => 'https://iwrf.id', 'description' => 'Koneksi ke ekosistem Indonesia Women Rights Forum.'],
                ['key' => 'idrf', 'label' => 'IDRF', 'href' => '/admin/koneksi/idrf', 'publicHref' => '/koneksi/idrf', 'sourceHref' => 'https://idrf.id', 'description' => 'Koneksi ke ekosistem Indonesia Development Research Forum.'],
                ['key' => 'simpul-pfb', 'label' => 'Simpul PFB', 'href' => '/admin/koneksi/simpul-pfb', 'publicHref' => '/koneksi/simpul-pfb', 'sourceHref' => $baseUrl.'/', 'description' => 'Kanal simpul dan jejaring pendukung berbasis wilayah.'],
                ['key' => 'baku-dapa', 'label' => 'Baku-Dapa', 'href' => '/admin/koneksi/baku-dapa', 'publicHref' => '/koneksi/baku-dapa', 'sourceHref' => 'https://baku-dapa.id', 'description' => 'Ruang siar, radio komunitas, dan koneksi narasi bersama.'],
                ['key' => 'telisik', 'label' => 'Telisik', 'href' => '/admin/koneksi/telisik', 'publicHref' => '/koneksi/telisik', 'sourceHref' => $baseUrl.'/', 'description' => 'Kanal observasi, pembacaan isu, dan penelusuran data.'],
                ['key' => 'sociopath', 'label' => 'Sociopath', 'href' => '/admin/koneksi/sociopath', 'publicHref' => '/koneksi/sociopath', 'sourceHref' => 'https://sociopath.id', 'description' => 'Platform sosial dan kanal kolaborasi ekosistem gerakan.'],
                ['key' => 'sake-mite', 'label' => 'Sake-Mite', 'href' => '/admin/koneksi/sake-mite', 'publicHref' => '/koneksi/sake-mite', 'sourceHref' => $baseUrl.'/', 'description' => 'Kanal koneksi komunitas dan pertukaran praktik baik.'],
                ['key' => 'civil-colony', 'label' => 'Civil Colony', 'href' => '/admin/koneksi/civil-colony', 'publicHref' => '/koneksi/civil-colony', 'sourceHref' => $baseUrl.'/', 'description' => 'Ruang kolektif untuk koneksi masyarakat sipil.'],
            ],
        ],
        ['key' => 'kolektif', 'label' => 'KOLEKTIF', 'href' => '/admin/kolektif', 'publicHref' => '/kolektif', 'sourceHref' => $baseUrl.'/', 'description' => 'Kelola narasi kolektif, testimoni simpul, dan arsip kolaborasi.'],
    ],
    'blog' => [
        ['id' => 1, 'title' => 'Scientists speculate that ours might not be held', 'img' => 'blog01.jpg', 'group' => 'blog', 'category' => 'Gaming', 'author' => 'miranda h.', 'date' => '25 April 2026'],
        ['id' => 2, 'title' => 'The Multiverse is the collection of alternate universes', 'img' => 'blog02.jpg', 'group' => 'blog', 'category' => 'Tech', 'author' => 'miranda h.', 'date' => '25 April 2026'],
        ['id' => 3, 'title' => 'That share a universal hierarchy a large variety of these', 'img' => 'blog03.jpg', 'group' => 'blog', 'category' => 'Movie', 'author' => 'miranda h.', 'date' => '25 April 2026'],
        ['id' => 4, 'title' => 'Universes were originated from another due to a major', 'img' => 'blog04.jpg', 'group' => 'blog', 'category' => 'Sports', 'author' => 'miranda h.', 'date' => '25 April 2026'],
        ['id' => 5, 'title' => 'A hypothetical collection of potentially diverse', 'img' => 'blog05.jpg', 'group' => 'blog', 'category' => 'Gaming', 'author' => 'miranda h.', 'date' => '25 April 2026'],
        ['id' => 6, 'title' => 'Stanford physicists Andrei Linde In a new study', 'img' => 'blog06.jpg', 'group' => 'blog', 'category' => 'Tech', 'author' => 'miranda h.', 'date' => '25 April 2026'],
    ],
    'page_contents' => [
        'profil' => [
            '_section' => [
                'eyebrow' => 'Profil CEA Indonesia',
                'title' => 'Profil Civic Engagement Alliance',
                'subtitle' => 'Latar pembentukan, mandat, nilai, struktur gerak, sumber daya, dan kanal kontak CEA Indonesia.',
                'body' => 'CEA adalah aliansi organisasi masyarakat sipil dari berbagai wilayah Indonesia yang bekerja bersama untuk merawat ruang sipil, demokrasi, keadilan sosial, dan kelestarian alam. Bagian profil merangkum sejarah, arah gerak, tata kelola, dan dokumen pengenal aliansi.',
                'image_path' => '/assets/img/cea/campur.png',
                'cards' => ['Riwayat', 'Mandat, Visi, Nilai', 'Struktur Gerak', 'Sumber Daya', 'Kontak'],
            ],
            'riwayat' => [
                'eyebrow' => 'Profil CEA Indonesia',
                'title' => 'Riwayat',
                'subtitle' => 'Proses pembentukan CEA dari pertemuan OMS di Sentul hingga Rembug Nasional di Lembang.',
                'body' => "Demokrasi Indonesia menghadapi tekanan berlapis: ruang sipil menyempit, indeks demokrasi menurun, dan penguasaan sumber daya alam makin timpang.\n\nPada Februari 2025, 48 organisasi masyarakat sipil bertemu di Sentul, Bogor, Jawa Barat, untuk mendiskusikan penyempitan ruang sipil dan kebutuhan platform koordinasi bersama.\n\nMandat itu ditindaklanjuti dalam Rembug Nasional OMS di Lembang pada 6-9 Juli 2025. Pertemuan yang menghadirkan 61 organisasi dari 19 provinsi tersebut menjadi tonggak lahirnya CEA sebagai aliansi nasional masyarakat sipil.",
                'image_path' => '/assets/img/cea/campur.png',
                'cards' => ['Latar', 'Februari 2025', '6-9 Juli 2025'],
            ],
            'mandat-visi-nilai' => [
                'eyebrow' => 'Visi & Mandat',
                'title' => 'Mandat, Visi, Nilai',
                'subtitle' => 'Visi CEA adalah ekosistem masyarakat sipil yang berdaya dan setara.',
                'body' => "CEA hadir dengan mandat utama untuk memperkuat ruang-ruang sipil di Indonesia agar lebih aman dan terbuka. Ruang sipil yang sehat mendorong keterlibatan warga yang bermakna sekaligus memperkuat ketahanan demokrasi.\n\nNilai kerja CEA mencakup niat yang murni, riang gembira, ketersalingan, menghebatkan yang lain, antirasisme, dan nondiskriminasi.",
                'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%285%29.png',
                'cards' => ['Niat yang murni', 'Riang gembira', 'Ketersalingan', 'Menghebatkan yang lain', 'Antirasisme dan nondiskriminasi'],
            ],
            'struktur-gerak' => [
                'eyebrow' => 'Struktur Gerak',
                'title' => 'Struktur Gerak CEA',
                'subtitle' => 'Jejaring simpul regional yang saling terhubung secara nasional.',
                'body' => "CEA merupakan gerakan sosial dan bukan organisasi resmi berbadan hukum. Aliansi ini bekerja sebagai jejaring simpul regional yang otonom, independen, namun tetap terikat tujuan dan nilai bersama.\n\nStruktur CEA bertumpu pada Jejaring Simpul Regional, Sekretariat Nasional, Gugus Tugas, dan Kaukus Isu. Kepemimpinan dijalankan secara kolektif melalui pertemuan reguler simpul dan rembug nasional.",
                'image_path' => '/assets/img/cea/struktur_gerak.png',
                'cards' => ['Jejaring Simpul Regional', 'Sekretariat Nasional', 'Gugus Tugas', 'Kaukus Isu'],
            ],
            'sumber-daya' => [
                'eyebrow' => 'Tata Kelola',
                'title' => 'Tata Kelola Sumber Daya',
                'subtitle' => 'Fokus, desentralisasi, pelokalan, dan subsidiaritas.',
                'body' => "Sumber daya CEA dikelola untuk mendukung penguatan kapasitas, penggalangan sumber daya tambahan, dan produksi bentuk-bentuk sumber daya baru secara kolektif.\n\nPrinsip desentralisasi menempatkan simpul regional sebagai aktor yang mandiri. Prinsip pelokalan dan subsidiaritas memastikan keputusan diambil sedekat mungkin dengan komunitas dan penerima manfaat.",
                'image_path' => '/assets/img/cea/tatakelola.png',
                'cards' => ['Fokus', 'Desentralisasi', 'Pelokalan', 'Kontribusi', 'Mobilisasi', 'Distribusi'],
            ],
            'kontak' => [
                'eyebrow' => 'Kontak',
                'title' => 'Hubungi Kami',
                'subtitle' => 'Sekretariat CEA Indonesia di Bantul, DI Yogyakarta.',
                'body' => "Sekretariat CEA Indonesia\nJl. Patih Singoranu No. 155\nTamanan, Banguntapan, Bantul\nDI Yogyakarta\n\nEmail: sekretariat@ceaindonesia.id",
                'image_path' => '/assets/img/cea/logo-non-bg.png',
                'cards' => ['Sekretariat', 'Surel', 'Kolaborasi', 'Informasi Publik'],
            ],
            'unduh-profil-id' => [
                'eyebrow' => 'Dokumen',
                'title' => 'Unduh Profil CEA Indonesia',
                'subtitle' => 'Dokumen profil CEA versi bahasa Indonesia.',
                'body' => 'Halaman ini disiapkan sebagai kanal unduhan profil CEA versi Indonesia. Dokumen profil merangkum riwayat, mandat, nilai, struktur, tata kelola sumber daya, dan arah aksi CEA.',
                'image_path' => '/assets/img/cea/1.png',
                'cards' => ['Profil ID', 'Versi ponsel', 'Dokumen pengenal'],
            ],
            'download-profile-en' => [
                'eyebrow' => 'Document',
                'title' => 'Download CEA Profile',
                'subtitle' => 'English profile document for Civic Engagement Alliance.',
                'body' => 'This page is prepared as the English profile download channel for CEA. It introduces the alliance, mandate, values, governance, and collective action agenda.',
                'image_path' => '/assets/img/cea/1.png',
                'cards' => ['English profile', 'Alliance brief', 'Public document'],
            ],
        ],
        'regio' => [
            '_section' => [
                'eyebrow' => 'Regio',
                'title' => 'Simpul Regional CEA',
                'subtitle' => 'Peta kerja simpul regional dan organisasi anggota CEA.',
                'body' => 'Regio adalah ruang konsolidasi OMS lokal, organisasi komunitas, forum, individu, dan kelompok masyarakat dalam jaringan CEA. Tiap simpul bekerja berdasarkan konteks wilayah, namun tetap terhubung secara nasional.',
                'image_path' => '/assets/img/cea/campur.png',
                'cards' => ['Simpul', 'Anggota', 'Focal Point', 'Wilayah Kerja'],
            ],
            'simpul' => [
                'eyebrow' => 'Regio',
                'title' => 'Simpul',
                'subtitle' => 'Peta simpul, focal point, dan wilayah kerja regional.',
                'body' => 'Simpul regional menjadi basis koordinasi CEA di tingkat wilayah. Simpul menghubungkan organisasi, komunitas, dan aktor lokal untuk memperkuat kerja kolektif dalam isu ruang sipil dan demokrasi.',
                'image_path' => '/assets/img/cea/campur.png',
                'cards' => ['Focal Point', 'Member', 'Peta Wilayah', 'Agenda Regional'],
            ],
            'anggota' => [
                'eyebrow' => 'Regio',
                'title' => 'Anggota',
                'subtitle' => 'Direktori organisasi anggota dan relasi simpul.',
                'body' => 'Anggota CEA terdiri dari organisasi masyarakat sipil, komunitas, forum, dan aktor yang bekerja lintas sektor pembangunan dan kemanusiaan. Direktori anggota dapat dikembangkan melalui panel admin.',
                'image_path' => '/assets/img/cea/campur.png',
                'cards' => ['Organisasi', 'Komunitas', 'Forum', 'Jejaring'],
            ],
        ],
        'siar' => [
            '_section' => [
                'eyebrow' => 'Siar',
                'title' => 'Siar CEA',
                'subtitle' => 'Kabar, rilis, prakarsa, refleksi, dan referensi dari ekosistem CEA.',
                'body' => 'Siar menjadi kanal publikasi CEA untuk membagikan kabar gerakan, rilis pers, prakarsa simpul, refleksi pembelajaran, dan bahan rujukan advokasi.',
                'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%285%29.png',
                'cards' => ['Kabar', 'Rilis', 'Prakarsa', 'Refleksi', 'Referensi'],
            ],
            'kabar' => ['eyebrow' => 'Siar', 'title' => 'Kabar', 'subtitle' => 'Kabar terbaru dari kegiatan dan jejaring CEA.', 'body' => 'Kanal kabar memuat catatan kegiatan, konsolidasi, pembaruan simpul, dan perkembangan kerja kolektif CEA di berbagai wilayah.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%285%29.png', 'cards' => ['Kegiatan', 'Konsolidasi', 'Simpul', 'Agenda']],
            'rilis' => ['eyebrow' => 'Siar', 'title' => 'Rilis', 'subtitle' => 'Rilis pers, pernyataan solidaritas, dan respons kelembagaan.', 'body' => 'Kanal rilis memuat sikap resmi, respons publik, dan pernyataan solidaritas CEA terhadap situasi yang berdampak pada ruang sipil dan demokrasi.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%286%29.png', 'cards' => ['Rilis Pers', 'Pernyataan', 'Solidaritas', 'Respons']],
            'prakarsa' => ['eyebrow' => 'Siar', 'title' => 'Prakarsa', 'subtitle' => 'Inisiatif dan praktik kolaboratif dari simpul CEA.', 'body' => 'Prakarsa berisi inisiatif, program, praktik baik, dan kerja-kerja eksperimen kolaboratif yang muncul dari simpul dan anggota CEA.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%287%29.png', 'cards' => ['Inisiatif', 'Program', 'Praktik Baik', 'Kolaborasi']],
            'refleksi' => ['eyebrow' => 'Siar', 'title' => 'Refleksi', 'subtitle' => 'Tulisan reflektif tentang ruang sipil, demokrasi, dan gerakan sosial.', 'body' => 'Refleksi menjadi ruang membaca ulang pengalaman gerakan, pembelajaran simpul, dinamika demokrasi, dan strategi masyarakat sipil.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%285%29.png', 'cards' => ['Pembelajaran', 'Demokrasi', 'Ruang Sipil', 'Gerakan Sosial']],
            'referensi' => ['eyebrow' => 'Siar', 'title' => 'Referensi', 'subtitle' => 'Bahan bacaan, dokumen pengetahuan, dan rujukan riset.', 'body' => 'Referensi memuat dokumen, bahan belajar, riset, dan rujukan untuk memperkuat kerja advokasi serta konsolidasi pengetahuan CEA.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%286%29.png', 'cards' => ['Dokumen', 'Riset', 'Bahan Bacaan', 'Rujukan']],
        ],
        'aksi' => [
            '_section' => ['eyebrow' => 'Aksi', 'title' => 'Aksi CEA', 'subtitle' => 'Manifesto, kajian strategis, gugus tugas, kaukus isu, dan diskursus publik.', 'body' => 'Aksi CEA diarahkan untuk membangun pengorganisasian basis, menguatkan kapasitas dan konektivitas OMS, memobilisasi sumber daya secara kolaboratif, serta mendorong kebijakan publik yang memperkuat ruang sipil.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%287%29.png', 'cards' => ['Manifesto', 'Kajian Strategis', 'Gugus Tugas', 'Kaukus Isu', 'Diskursus']],
            'manifesto' => ['eyebrow' => 'Aksi', 'title' => 'Manifesto', 'subtitle' => 'Narasi dasar, posisi gerakan, dan arah aksi CEA.', 'body' => 'Manifesto CEA menegaskan kebutuhan membangun gerakan masyarakat sipil yang berdaya, setara, berakar pada lokalitas, terkoneksi regional hingga nasional, dan dikelola secara kolaboratif.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%287%29.png', 'cards' => ['Ruang Sipil', 'Demokrasi', 'Keadilan Sosial', 'Kelestarian Alam']],
            'kajian-strategis' => ['eyebrow' => 'Aksi', 'title' => 'Kajian Strategis', 'subtitle' => 'Analisis isu prioritas aliansi.', 'body' => 'Kajian strategis disiapkan untuk membaca dinamika kebijakan, ketimpangan, ruang sipil, demokrasi, serta isu sektoral yang menjadi perhatian simpul dan anggota CEA.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%285%29.png', 'cards' => ['Analisis', 'Kebijakan', 'Advokasi', 'Data']],
            'gugus-tugas' => ['eyebrow' => 'Aksi', 'title' => 'Gugus Tugas', 'subtitle' => 'Kelompok kerja civic space dan civic engagement.', 'body' => "Gugus Tugas bekerja dalam dua arena: Civic Space dan Civic Engagement. Arena ini mencakup pengorganisasian komunitas, pendidikan kritis, peningkatan kapasitas, mobilisasi sumber daya, advokasi kebijakan, konsolidasi narasi, dan demokrasi ekonomi.", 'image_path' => '/assets/img/cea/struktur_gerak.png', 'cards' => ['Civic Space', 'Civic Engagement', 'Advokasi', 'Mobilisasi Resource']],
            'kaukus-isu' => ['eyebrow' => 'Aksi', 'title' => 'Kaukus Isu', 'subtitle' => 'Kaukus tematik dan kanal isu lintas sektor.', 'body' => 'Kaukus Isu adalah kelompok kerja kajian dan advokasi tematik berbasis isu sektoral, seperti HAM, GEDSI, kesehatan, pendidikan, kehutanan, pesisir, energi, kemanusiaan, dan isu prioritas lain.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%286%29.png', 'cards' => ['HAM', 'GEDSI', 'Lingkungan', 'Kemanusiaan']],
            'diskursus' => ['eyebrow' => 'Aksi', 'title' => 'Diskursus', 'subtitle' => 'Forum diskusi, percakapan publik, dan agenda pengetahuan.', 'body' => 'Diskursus menjadi ruang percakapan publik untuk menguji gagasan, memperkaya strategi, dan membangun pengetahuan bersama di antara simpul, anggota, dan mitra CEA.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%285%29.png', 'cards' => ['Forum', 'Diskusi', 'Pengetahuan', 'Strategi']],
        ],
        'koneksi' => [
            '_section' => ['eyebrow' => 'Koneksi', 'title' => 'Koneksi Ekosistem', 'subtitle' => 'Platform kolaborasi dan kanal mitra CEA.', 'body' => 'Koneksi menghimpun platform, kanal, dan jejaring mitra yang memperluas daya kerja CEA dalam penggalangan sumber daya, pengetahuan, media komunitas, riset, dan kolaborasi lintas isu.', 'image_path' => '/assets/img/cea/tatakelola.png', 'cards' => ['Lokadana', 'IWRF', 'IDRF', 'Baku-Dapa', 'Sociopath', 'Civil Colony']],
            'lokadana' => ['eyebrow' => 'Koneksi', 'title' => 'Lokadana', 'subtitle' => 'Platform hibah partisipatif dan mobilisasi sumber daya.', 'body' => 'Lokadana menjadi salah satu kanal koneksi untuk mendukung mobilisasi sumber daya dan model pendanaan partisipatif yang relevan bagi gerakan masyarakat sipil.', 'image_path' => '/assets/img/cea/tatakelola.png', 'cards' => ['Hibah', 'Partisipatif', 'Mobilisasi', 'Sumber Daya']],
            'iwrf' => ['eyebrow' => 'Koneksi', 'title' => 'IWRF', 'subtitle' => 'Koneksi ke ekosistem Indonesia Women Rights Forum.', 'body' => 'IWRF menjadi bagian dari koneksi ekosistem yang memperkuat perspektif hak perempuan, GEDSI, dan kerja lintas organisasi.', 'image_path' => '/assets/img/cea/campur.png', 'cards' => ['Hak Perempuan', 'GEDSI', 'Forum', 'Ekosistem']],
            'idrf' => ['eyebrow' => 'Koneksi', 'title' => 'IDRF', 'subtitle' => 'Koneksi ke ekosistem Indonesia Development Research Forum.', 'body' => 'IDRF menghubungkan kerja riset, pembangunan, pembelajaran, dan pengetahuan untuk memperkuat basis data serta argumentasi kebijakan.', 'image_path' => '/assets/img/cea/campur.png', 'cards' => ['Riset', 'Pembangunan', 'Pengetahuan', 'Kebijakan']],
            'simpul-pfb' => ['eyebrow' => 'Koneksi', 'title' => 'Simpul PFB', 'subtitle' => 'Kanal simpul dan jejaring pendukung berbasis wilayah.', 'body' => 'Simpul PFB disiapkan sebagai kanal koneksi untuk memperkuat koordinasi, pertukaran informasi, dan jejaring pendukung berbasis wilayah.', 'image_path' => '/assets/img/cea/campur.png', 'cards' => ['Simpul', 'Wilayah', 'Koordinasi', 'Jejaring']],
            'baku-dapa' => ['eyebrow' => 'Koneksi', 'title' => 'Baku-Dapa', 'subtitle' => 'Ruang siar, radio komunitas, dan koneksi narasi bersama.', 'body' => 'Baku-Dapa memperkuat kerja narasi, ruang dengar, dan kanal komunikasi komunitas dalam ekosistem gerakan.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%285%29.png', 'cards' => ['Radio Komunitas', 'Ruang Siar', 'Narasi', 'Komunitas']],
            'telisik' => ['eyebrow' => 'Koneksi', 'title' => 'Telisik', 'subtitle' => 'Kanal observasi, pembacaan isu, dan penelusuran data.', 'body' => 'Telisik menjadi kanal untuk mengamati dinamika isu, membaca data, dan menyusun pengetahuan awal bagi advokasi serta respons gerakan.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%286%29.png', 'cards' => ['Observasi', 'Data', 'Isu', 'Analisis']],
            'sociopath' => ['eyebrow' => 'Koneksi', 'title' => 'Sociopath', 'subtitle' => 'Platform sosial dan kanal kolaborasi ekosistem gerakan.', 'body' => 'Sociopath menjadi kanal koneksi sosial untuk memperluas jejaring, kolaborasi, dan pertukaran praktik dalam ekosistem gerakan.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%287%29.png', 'cards' => ['Platform Sosial', 'Kolaborasi', 'Jejaring', 'Praktik']],
            'sake-mite' => ['eyebrow' => 'Koneksi', 'title' => 'Sake-Mite', 'subtitle' => 'Kanal koneksi komunitas dan pertukaran praktik baik.', 'body' => 'Sake-Mite disiapkan sebagai ruang koneksi komunitas untuk saling bertukar praktik, pengalaman, dan pembelajaran antaraktor lokal.', 'image_path' => '/assets/img/cea/campur.png', 'cards' => ['Komunitas', 'Praktik Baik', 'Pertukaran', 'Pembelajaran']],
            'civil-colony' => ['eyebrow' => 'Koneksi', 'title' => 'Civil Colony', 'subtitle' => 'Ruang kolektif untuk koneksi masyarakat sipil.', 'body' => 'Civil Colony menjadi ruang kolektif untuk mempertemukan gagasan, kerja, dan koneksi masyarakat sipil lintas wilayah serta lintas isu.', 'image_path' => '/assets/img/cea/campur.png', 'cards' => ['Ruang Kolektif', 'Masyarakat Sipil', 'Gagasan', 'Koneksi']],
        ],
        'kolektif' => [
            '_section' => ['eyebrow' => 'Kolektif', 'title' => 'Kolektif', 'subtitle' => 'Narasi kolektif, testimoni simpul, dan arsip kolaborasi.', 'body' => 'Kolektif menjadi ruang untuk menghimpun cerita, testimoni, refleksi, dan arsip kolaborasi dari simpul, anggota, serta mitra CEA.', 'image_path' => '/assets/img/cea/campur.png', 'cards' => ['Narasi', 'Testimoni', 'Arsip', 'Kolaborasi']],
        ],
    ],
];
