<?php

$baseUrl = 'https://ceaindonesia.id';

return [
    'navigation' => [
        ['key' => 'beranda', 'label' => 'BERANDA', 'href' => '/', 'sourceHref' => $baseUrl.'/', 'description' => 'Halaman utama Pooling Fund - KSO dan ringkasan mandat kolektif.'],
        [
            'key' => 'profil',
            'label' => 'PROFIL KSO',
            'href' => '/admin/profil',
            'publicHref' => '/profil',
            'sourceHref' => $baseUrl.'/riwayat/',
            'description' => 'Kelola profil, mandat, visi, misi, struktur gerak, sumber daya, kontak, dan dokumen Pooling Fund - KSO.',
            'children' => [
                ['key' => 'riwayat', 'label' => 'Profil KSO', 'href' => '/admin/profil/riwayat', 'publicHref' => '/profil/riwayat', 'sourceHref' => $baseUrl.'/riwayat/', 'description' => 'Profil Pooling Fund - KSO sebagai platform mandat kolektif antar CSO.'],
                ['key' => 'mandat-visi-nilai', 'label' => 'Mandat, Visi, Misi', 'href' => '/admin/profil/mandat-visi-nilai', 'publicHref' => '/profil/mandat-visi-nilai', 'sourceHref' => $baseUrl.'/mandat-visi-nilai-cea/', 'description' => 'Mandat kolektif, visi, misi, tujuan, prinsip, dan karakter KSO-Pooling Fund.'],
                ['key' => 'tujuan-prinsip', 'label' => 'Tujuan & Prinsip', 'href' => '/admin/profil/tujuan-prinsip', 'publicHref' => '/profil/tujuan-prinsip', 'sourceHref' => $baseUrl.'/', 'description' => 'Tujuan pembentukan, prinsip, dan karakter KSO-Pooling Fund.'],
                ['key' => 'struktur-gerak', 'label' => 'Arsitektur Mandat', 'href' => '/admin/profil/struktur-gerak', 'publicHref' => '/profil/struktur-gerak', 'sourceHref' => $baseUrl.'/struktur-gerak-cea/', 'description' => 'Arsitektur mandat kolektif, simpul regional, forum anggota, komite, dan administrator.'],
                ['key' => 'sumber-daya', 'label' => 'Tata Kelola Sumber Daya', 'href' => '/admin/profil/sumber-daya', 'publicHref' => '/profil/sumber-daya', 'sourceHref' => $baseUrl.'/tata-kelola-sumber-daya-cea/', 'description' => 'Tata kelola sumber daya sebagai mandat kolektif untuk ekosistem kemanusiaan dan kepemimpinan lokal.'],
                ['key' => 'kontak', 'label' => 'Kontak', 'href' => '/admin/profil/kontak', 'publicHref' => '/profil/kontak', 'sourceHref' => $baseUrl.'/kontak/', 'description' => 'Alamat sekretariat, kanal kontak, dan informasi penghubung publik.'],
            ],
        ],
        [
            'key' => 'regio',
            'label' => 'SIMPUL REGION',
            'href' => '/admin/regio',
            'publicHref' => '/regio',
            'sourceHref' => $baseUrl.'/',
            'description' => 'Kelola data simpul regional dan organisasi anggota Pooling Fund - KSO.',
            'children' => [
                ['key' => 'simpul', 'label' => 'Sebaran Simpul', 'href' => '/admin/regio/simpul', 'publicHref' => '/regio/simpul', 'sourceHref' => $baseUrl.'/', 'description' => 'Sebaran region, anggota simpul, wilayah kerja, dan status regional.'],
                ['key' => 'anggota', 'label' => 'Anggota', 'href' => '/admin/regio/anggota', 'publicHref' => '/regio/anggota', 'sourceHref' => $baseUrl.'/', 'description' => 'Direktori organisasi anggota, profil lembaga, dan relasi simpul.'],
            ],
        ],
    ],
    'blog' => [
        ['id' => 1, 'title' => 'Scientists speculate that ours might not be held', 'img' => 'blog01.jpg', 'group' => 'blog', 'category' => 'Gaming', 'author' => 'miranda h.', 'date' => '25 April 2026'],
        ['id' => 2, 'title' => 'The Multiverse is the collection of alternate universes', 'img' => 'blog02.jpg', 'group' => 'blog', 'category' => 'Tech', 'author' => 'miranda h.', 'date' => '25 April 2026'],
        ['id' => 3, 'title' => 'That share a universal hierarchy a large variety of these', 'img' => 'blog03.jpg', 'group' => 'blog', 'category' => 'Movie', 'author' => 'miranda h.', 'date' => '25 April 2026'],
        ['id' => 4, 'title' => 'Universes were originated from another due to a major', 'img' => 'blog04.jpg', 'group' => 'blog', 'category' => 'Sports', 'author' => 'miranda h.', 'date' => '25 April 2026'],
        ['id' => 5, 'title' => 'A hypothetical collection of potentially diverse', 'img' => 'blog05.jpg', 'group' => 'blog', 'category' => 'Gaming', 'author' => 'miranda h.', 'date' => '25 April 2026'],
        ['id' => 6, 'title' => 'Stanford physicists Andrei Linde In a new study', 'img' => 'blog06.jpg', 'group' => 'blog', 'category' => 'Tech', 'author' => 'miranda h.', 'date' => '25 April 2026'],
    ],
    'page_contents' => [
        'profil' => [
            '_section' => [
                'eyebrow' => 'Profil KSO-Pooling Fund',
                'title' => 'Pooling Fund - KSO',
                'subtitle' => 'Platform mandat kolektif antar CSO untuk menghimpun dan menyalurkan dana kemanusiaan secara bersama.',
                'body' => "Perubahan besar tidak lahir dari satu lembaga, tapi dari ekosistem yang terhubung.\n\nPooling Fund - KSO adalah platform mandat kolektif antar CSO untuk menghimpun dan menyalurkan dana kemanusiaan secara bersama, berbasis kebutuhan komunitas dan kepemimpinan lokal, tanpa membentuk badan hukum baru.\n\nTagline: Menguatkan Lokal, Memperluas Dampak.",
                'image_path' => '/assets/img/cea/campur.png',
                'cards' => ['Mandat Kolektif', 'Kepemimpinan Lokal', 'Respon Kemanusiaan', 'Transparansi', 'Akuntabilitas'],
            ],
            'riwayat' => [
                'eyebrow' => 'Profil KSO-Pooling Fund',
                'title' => 'Profil Pooling Fund - KSO',
                'subtitle' => 'Platform kerja sama operasional yang menghubungkan simpul kekuatan sipil di berbagai wilayah Indonesia.',
                'body' => "Pooling Fund - KSO bukanlah sebuah entitas tunggal yang hierarkis, melainkan infrastruktur bersama yang menghubungkan simpul-simpul kekuatan sipil di berbagai wilayah Indonesia.\n\nSebagai platform kerja sama operasional, struktur ini didesain untuk menjaga kedaulatan setiap organisasi anggota sambil memperkuat daya tawar kolektif dalam pengelolaan sumber daya kemanusiaan.\n\nKSO bergerak melalui tujuh simpul regional yang bersifat otonom dan independen, namun terikat dalam satu nafas visi yang sama: mewujudkan kepemimpinan lokal yang berkeadilan.",
                'image_path' => '/assets/img/cea/campur.png',
                'cards' => ['Tanpa Badan Hukum Baru', 'Berbasis Komunitas', 'Kepemimpinan Lokal', 'Tujuh Simpul Regional'],
            ],
            'mandat-visi-nilai' => [
                'eyebrow' => 'Mandat, Visi, Misi',
                'title' => 'Mandat, Visi, Misi KSO-Pooling Fund',
                'subtitle' => 'Satu mandat kolektif untuk kepemimpinan lokal dan respon kemanusiaan yang berkeadilan.',
                'body' => "Mandat PF-KSO adalah memperkuat kepemimpinan lokal, membangun ekosistem kolaborasi sosial, dan mendorong respon kemanusiaan yang adil, inklusif, serta berakar pada komunitas.\n\nVisi: Satu mandat kolektif untuk kepemimpinan lokal dan respon kemanusiaan yang berkeadilan.\n\nMisi: memperkuat kepemimpinan lokal dan peran komunitas dalam respon sosial dan kemanusiaan; membangun ekosistem kolaborasi multipihak yang inklusif, setara, dan berbasis kepercayaan; mengembangkan pendekatan pooling fund dan pengelolaan sumber daya bersama yang transparan dan akuntabel; mendorong pertukaran pengetahuan, penguatan kapasitas, dan pembelajaran kolektif antar komunitas dan organisasi; serta memastikan respon kemanusiaan dan pembangunan sosial lebih adil, partisipatif, dan berpihak pada kelompok rentan.\n\nTujuan pembentukan KSO-Pooling Fund adalah menghimpun dan mengelola dana kemanusiaan secara cepat, transparan, dan akuntabel; membagi risiko dan tanggung jawab operasional serta tata kelola secara kolektif; memperkuat local leadership dalam respon bencana kemanusiaan; mengurangi fragmentasi respon; menjadi satu pintu komunikasi ke donor dan publik sekaligus instrumen kepercayaan; serta menjadi model transisi menuju kelembagaan pooling fund yang lebih mapan.\n\nPrinsip dan karakter KSO-Pooling Fund meliputi kesetaraan antar anggota, satu CSO satu suara, berbasis kebutuhan komunitas, kecepatan sebagai nilai utama, transparansi sebagai aset strategis, akuntabilitas kolektif, serta local leadership dan local first.",
                'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%285%29.png',
                'cards' => ['Mandat Kolektif', 'Visi Berkeadilan', 'Misi Kolaboratif', 'Tujuan Pembentukan', 'Local First'],
            ],
            'tujuan-prinsip' => [
                'eyebrow' => 'Tujuan & Prinsip',
                'title' => 'Tujuan, Prinsip, dan Karakter KSO-Pooling Fund',
                'subtitle' => 'Fondasi kerja kolektif untuk respon kemanusiaan yang cepat, transparan, akuntabel, dan berakar pada komunitas.',
                'body' => "KSO-Pooling Fund dibentuk untuk menghimpun dan mengelola dana kemanusiaan secara cepat, transparan, dan akuntabel.\n\nPlatform ini membagi risiko, tanggung jawab operasional, dan tata kelola secara kolektif; memperkuat kepemimpinan lokal dalam respon bencana kemanusiaan; mengurangi fragmentasi respon; menjadi satu pintu komunikasi ke donor dan publik sekaligus instrumen kepercayaan; serta menjadi model transisi menuju kelembagaan pooling fund yang lebih mapan.\n\nPrinsip dan karakter KSO-Pooling Fund adalah kesetaraan antar anggota, satu CSO satu suara, berbasis kebutuhan komunitas, kecepatan sebagai nilai utama, transparansi sebagai aset strategis, akuntabilitas kolektif, serta local leadership dan local first.",
                'image_path' => '/assets/img/cea/tatakelola.png',
                'cards' => ['Cepat dan Akuntabel', 'Berbagi Risiko', 'Local Leadership', 'Trust Building', 'Satu CSO Satu Suara', 'Local First'],
            ],
            'struktur-gerak' => [
                'eyebrow' => 'Struktur Gerak',
                'title' => 'Arsitektur Mandat Kolektif',
                'subtitle' => 'Tujuh simpul regional yang otonom, independen, dan terhubung dalam satu visi kepemimpinan lokal.',
                'body' => "Pooling Fund KSO bukanlah entitas tunggal yang hierarkis, melainkan infrastruktur bersama yang menghubungkan simpul-simpul kekuatan sipil di berbagai wilayah Indonesia.\n\nArsitektur ini menjaga kedaulatan setiap organisasi anggota sambil memperkuat daya tawar kolektif dalam pengelolaan sumber daya kemanusiaan. Setiap simpul regional bekerja secara otonom dan independen, namun terikat pada visi yang sama.\n\nPrinsip gerak kami mencakup mandat kolektif melalui Forum Anggota dengan prinsip one organization, one vote; pemisahan peran antara fungsi strategis Forum dan Komite dengan fungsi operasional Administrator; serta ketahanan ekosistem melalui pertukaran pembelajaran, risiko, dan tanggung jawab antar simpul regional.",
                'image_path' => '/assets/img/cea/struktur_gerak.png',
                'cards' => ['Forum Anggota', 'Komite', 'Administrator', 'Simpul Regional', 'One Organization One Vote'],
            ],
            'sumber-daya' => [
                'eyebrow' => 'Tata Kelola',
                'title' => 'Tata Kelola Sumber Daya',
                'subtitle' => 'Sumber daya ditempatkan sebagai mandat kolektif untuk memperkuat ekosistem kemanusiaan dan kepemimpinan lokal.',
                'body' => "KSO menempatkan sumber daya bukan sebagai aset lembaga, melainkan mandat kolektif untuk memperkuat ekosistem kemanusiaan dan kepemimpinan lokal.\n\nPengambilan keputusan dilakukan oleh mereka yang paling dekat dengan krisis, sehingga dana dikelola secara transparan demi kedaulatan serta ketangguhan komunitas di setiap wilayah.\n\nPendekatan ini memperkuat kecepatan respon, akuntabilitas kolektif, serta kepercayaan donor dan publik terhadap kerja kemanusiaan yang dipimpin dari lokal.",
                'image_path' => '/assets/img/cea/tatakelola.png',
                'cards' => ['Mandat Kolektif', 'Transparansi', 'Akuntabilitas', 'Kedaulatan Komunitas', 'Ketangguhan Wilayah'],
            ],
            'kontak' => [
                'eyebrow' => 'Kontak',
                'title' => 'Hubungi Kami',
                'subtitle' => 'Sekretariat Pooling Fund - KSO di Bantul, DI Yogyakarta.',
                'body' => "Sekretariat Pooling Fund - KSO\nJl. Patih Singoranu No. 155\nTamanan, Banguntapan, Bantul\nDI Yogyakarta\n\nEmail: sekretariat@ceaindonesia.id",
                'image_path' => '/assets/img/cea/logo-non-bg.png',
                'cards' => ['Sekretariat', 'Surel', 'Kolaborasi', 'Informasi Publik'],
            ],
            'unduh-profil-id' => [
                'eyebrow' => 'Dokumen',
                'title' => 'Unduh Profil KSO-Pooling Fund',
                'subtitle' => 'Dokumen profil Pooling Fund - KSO versi bahasa Indonesia.',
                'body' => 'Halaman ini disiapkan sebagai kanal unduhan profil Pooling Fund - KSO versi Indonesia. Dokumen profil merangkum mandat kolektif, visi, misi, tujuan, prinsip, struktur gerak, dan tata kelola sumber daya.',
                'image_path' => '/assets/img/cea/1.png',
                'cards' => ['Profil ID', 'Versi ponsel', 'Dokumen pengenal'],
            ],
            'download-profile-en' => [
                'eyebrow' => 'Document',
                'title' => 'Download KSO-Pooling Fund Profile',
                'subtitle' => 'English profile document for Pooling Fund - KSO.',
                'body' => 'This page is prepared as the English profile download channel for Pooling Fund - KSO. It introduces the collective mandate, vision, mission, governance, and humanitarian resource pooling agenda.',
                'image_path' => '/assets/img/cea/1.png',
                'cards' => ['English profile', 'Alliance brief', 'Public document'],
            ],
        ],
        'regio' => [
            '_section' => [
                'eyebrow' => 'Regio',
                'title' => 'Simpul Regional Pooling Fund - KSO',
                'subtitle' => 'Peta kerja simpul regional dan organisasi anggota Pooling Fund - KSO.',
                'body' => 'Regio adalah ruang konsolidasi OMS lokal, organisasi komunitas, forum, individu, dan kelompok masyarakat dalam jaringan Pooling Fund - KSO. Tiap simpul bekerja berdasarkan konteks wilayah, namun tetap terhubung secara nasional.',
                'image_path' => '/assets/img/cea/campur.png',
                'cards' => ['Simpul', 'Anggota', 'Focal Point', 'Wilayah Kerja'],
            ],
            'simpul' => [
                'eyebrow' => 'Regio',
                'title' => 'Sebaran Region Simpul KSO-Pooling Fund',
                'subtitle' => 'Daftar simpul regional dan anggota KSO-Pooling Fund di berbagai wilayah Indonesia.',
                'body' => "1. KSO-Pooling Fund SUMBAGSEL (Sumatera Bagian Selatan) \"Tangguh\"\nAnggota:\n1. Yayasan Peduli Kemandirian Masyarakat (YAPEMMAS) Medan\n2. Yayasan Fajar Sejahtera Indonesia (YAFSI)-Medan\n3. WALHI Sumbar\n4. WALHI SUMUT\n5. FLOWER Aceh\n6. Yayasan Perempuan dan Anak Negeri (YPANBA) Aceh\n\n2. KSO-Pooling Fund SUMBAGSEL (Sumatera Bagian Selatan) \"Pulih dan Lestari\"\nAnggota:\n1. WALHI Lampung\n2. LBH Bandar Lampung\n3. PKBI Lampung\n4. WALHI Bengkulu\n5. YKWS Lampung\n\n3. KSO-Pooling Fund Region Papua (KSO Tanah Papua)\nAnggota:\n1. LEKAT Jayapura\n2. KIPRA Jayapura\n3. YAPMI Jayapura\n4. GEMAPALA Fakfak\n5. YAPARI Sorong\n6. PERDU Manokwari\n7. KOMPAK Nabire\n8. HUMI INANE Wamena\n\n4. KSO-Pooling Fund Region Kalimantan (Solidaritas Kemanusiaan Borneo)\nAnggota:\n1. WALHI Kalbar\n2. WALHI Kalsel\n3. WALHI Kalteng\n4. WALHI Kaltim\n5. ELPAGAR KalBar\n6. BORNEO Institute Kalteng\n7. PIONIR Bulungan Kaltara\n\n5. KSO-Pooling Fund Region Jawa\nAnggota:\n1. WALHI Jatim\n2. WALHI Jogjakarta\n3. LBH Semarang\n4. LBH Surabaya\n5. LBH Jogjakarta\n6. Yayasan EPIK\n7. KPI Jabar\n\n6. KSO-Pooling Fund Region Sulawesi\n\n7. KSO-Pooling Fund Region Bali Nusra",
                'image_path' => '/assets/img/cea/campur.png',
                'cards' => ['Sumbagsel Tangguh', 'Sumbagsel Pulih dan Lestari', 'Tanah Papua', 'Solidaritas Kemanusiaan Borneo', 'Jawa', 'Sulawesi', 'Bali Nusra'],
            ],
            'anggota' => [
                'eyebrow' => 'Regio',
                'title' => 'Anggota',
                'subtitle' => 'Direktori organisasi anggota dan relasi simpul.',
                'body' => 'Anggota Pooling Fund - KSO terdiri dari organisasi masyarakat sipil, komunitas, forum, dan aktor yang bekerja lintas sektor pembangunan dan kemanusiaan. Direktori anggota dapat dikembangkan melalui panel admin.',
                'image_path' => '/assets/img/cea/campur.png',
                'cards' => ['Organisasi', 'Komunitas', 'Forum', 'Jejaring'],
            ],
        ],
        'siar' => [
            '_section' => [
                'eyebrow' => 'Siar',
                'title' => 'Siar Pooling Fund - KSO',
                'subtitle' => 'Kabar, rilis, prakarsa, refleksi, dan referensi dari ekosistem Pooling Fund - KSO.',
                'body' => 'Siar menjadi kanal publikasi Pooling Fund - KSO untuk membagikan kabar gerakan, rilis pers, prakarsa simpul, refleksi pembelajaran, dan bahan rujukan advokasi.',
                'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%285%29.png',
                'cards' => ['Kabar', 'Rilis', 'Prakarsa', 'Refleksi', 'Referensi'],
            ],
            'kabar' => ['eyebrow' => 'Siar', 'title' => 'Kabar', 'subtitle' => 'Kabar terbaru dari kegiatan dan jejaring Pooling Fund - KSO.', 'body' => 'Kanal kabar memuat catatan kegiatan, konsolidasi, pembaruan simpul, dan perkembangan kerja kolektif Pooling Fund - KSO di berbagai wilayah.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%285%29.png', 'cards' => ['Kegiatan', 'Konsolidasi', 'Simpul', 'Agenda']],
            'rilis' => ['eyebrow' => 'Siar', 'title' => 'Rilis', 'subtitle' => 'Rilis pers, pernyataan solidaritas, dan respons kelembagaan.', 'body' => 'Kanal rilis memuat sikap resmi, respons publik, dan pernyataan solidaritas Pooling Fund - KSO terhadap situasi yang berdampak pada ruang sipil dan demokrasi.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%286%29.png', 'cards' => ['Rilis Pers', 'Pernyataan', 'Solidaritas', 'Respons']],
            'prakarsa' => ['eyebrow' => 'Siar', 'title' => 'Prakarsa', 'subtitle' => 'Inisiatif dan praktik kolaboratif dari simpul Pooling Fund - KSO.', 'body' => 'Prakarsa berisi inisiatif, program, praktik baik, dan kerja-kerja eksperimen kolaboratif yang muncul dari simpul dan anggota Pooling Fund - KSO.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%287%29.png', 'cards' => ['Inisiatif', 'Program', 'Praktik Baik', 'Kolaborasi']],
            'refleksi' => ['eyebrow' => 'Siar', 'title' => 'Refleksi', 'subtitle' => 'Tulisan reflektif tentang ruang sipil, demokrasi, dan gerakan sosial.', 'body' => 'Refleksi menjadi ruang membaca ulang pengalaman gerakan, pembelajaran simpul, dinamika demokrasi, dan strategi masyarakat sipil.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%285%29.png', 'cards' => ['Pembelajaran', 'Demokrasi', 'Ruang Sipil', 'Gerakan Sosial']],
            'referensi' => ['eyebrow' => 'Siar', 'title' => 'Referensi', 'subtitle' => 'Bahan bacaan, dokumen pengetahuan, dan rujukan riset.', 'body' => 'Referensi memuat dokumen, bahan belajar, riset, dan rujukan untuk memperkuat kerja advokasi serta konsolidasi pengetahuan Pooling Fund - KSO.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%286%29.png', 'cards' => ['Dokumen', 'Riset', 'Bahan Bacaan', 'Rujukan']],
        ],
        'aksi' => [
            '_section' => ['eyebrow' => 'Aksi', 'title' => 'Aksi Pooling Fund - KSO', 'subtitle' => 'Manifesto, kajian strategis, gugus tugas, kaukus isu, dan diskursus publik.', 'body' => 'Aksi Pooling Fund - KSO diarahkan untuk membangun pengorganisasian basis, menguatkan kapasitas dan konektivitas OMS, memobilisasi sumber daya secara kolaboratif, serta mendorong kebijakan publik yang memperkuat ruang sipil.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%287%29.png', 'cards' => ['Manifesto', 'Kajian Strategis', 'Gugus Tugas', 'Kaukus Isu', 'Diskursus']],
            'manifesto' => ['eyebrow' => 'Aksi', 'title' => 'Manifesto', 'subtitle' => 'Narasi dasar, posisi gerakan, dan arah aksi Pooling Fund - KSO.', 'body' => 'Manifesto Pooling Fund - KSO menegaskan kebutuhan membangun gerakan masyarakat sipil yang berdaya, setara, berakar pada lokalitas, terkoneksi regional hingga nasional, dan dikelola secara kolaboratif.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%287%29.png', 'cards' => ['Ruang Sipil', 'Demokrasi', 'Keadilan Sosial', 'Kelestarian Alam']],
            'kajian-strategis' => ['eyebrow' => 'Aksi', 'title' => 'Kajian Strategis', 'subtitle' => 'Analisis isu prioritas aliansi.', 'body' => 'Kajian strategis disiapkan untuk membaca dinamika kebijakan, ketimpangan, ruang sipil, demokrasi, serta isu sektoral yang menjadi perhatian simpul dan anggota Pooling Fund - KSO.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%285%29.png', 'cards' => ['Analisis', 'Kebijakan', 'Advokasi', 'Data']],
            'gugus-tugas' => ['eyebrow' => 'Aksi', 'title' => 'Gugus Tugas', 'subtitle' => 'Kelompok kerja civic space dan civic engagement.', 'body' => "Gugus Tugas bekerja dalam dua arena: Civic Space dan Civic Engagement. Arena ini mencakup pengorganisasian komunitas, pendidikan kritis, peningkatan kapasitas, mobilisasi sumber daya, advokasi kebijakan, konsolidasi narasi, dan demokrasi ekonomi.", 'image_path' => '/assets/img/cea/struktur_gerak.png', 'cards' => ['Civic Space', 'Civic Engagement', 'Advokasi', 'Mobilisasi Resource']],
            'kaukus-isu' => ['eyebrow' => 'Aksi', 'title' => 'Kaukus Isu', 'subtitle' => 'Kaukus tematik dan kanal isu lintas sektor.', 'body' => 'Kaukus Isu adalah kelompok kerja kajian dan advokasi tematik berbasis isu sektoral, seperti HAM, GEDSI, kesehatan, pendidikan, kehutanan, pesisir, energi, kemanusiaan, dan isu prioritas lain.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%286%29.png', 'cards' => ['HAM', 'GEDSI', 'Lingkungan', 'Kemanusiaan']],
            'diskursus' => ['eyebrow' => 'Aksi', 'title' => 'Diskursus', 'subtitle' => 'Forum diskusi, percakapan publik, dan agenda pengetahuan.', 'body' => 'Diskursus menjadi ruang percakapan publik untuk menguji gagasan, memperkaya strategi, dan membangun pengetahuan bersama di antara simpul, anggota, dan mitra Pooling Fund - KSO.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%285%29.png', 'cards' => ['Forum', 'Diskusi', 'Pengetahuan', 'Strategi']],
        ],
        'koneksi' => [
            '_section' => ['eyebrow' => 'Koneksi', 'title' => 'Koneksi Ekosistem', 'subtitle' => 'Platform kolaborasi dan kanal mitra Pooling Fund - KSO.', 'body' => 'Koneksi menghimpun platform, kanal, dan jejaring mitra yang memperluas daya kerja Pooling Fund - KSO dalam penggalangan sumber daya, pengetahuan, media komunitas, riset, dan kolaborasi lintas isu.', 'image_path' => '/assets/img/cea/tatakelola.png', 'cards' => ['Lokadana', 'IWRF', 'IDRF', 'Baku-Dapa', 'Sociopath', 'Civil Colony']],
            'lokadana' => ['eyebrow' => 'Koneksi', 'title' => 'Lokadana', 'subtitle' => 'Platform hibah partisipatif dan mobilisasi sumber daya.', 'body' => 'Lokadana menjadi salah satu kanal koneksi untuk mendukung mobilisasi sumber daya dan model pendanaan partisipatif yang relevan bagi gerakan masyarakat sipil.', 'image_path' => '/assets/img/cea/tatakelola.png', 'cards' => ['Hibah', 'Partisipatif', 'Mobilisasi', 'Sumber Daya']],
            'iwrf' => ['eyebrow' => 'Koneksi', 'title' => 'IWRF', 'subtitle' => 'Koneksi ke ekosistem Indonesia Women Rights Forum.', 'body' => 'IWRF menjadi bagian dari koneksi ekosistem yang memperkuat perspektif hak perempuan, GEDSI, dan kerja lintas organisasi.', 'image_path' => '/assets/img/cea/campur.png', 'cards' => ['Hak Perempuan', 'GEDSI', 'Forum', 'Ekosistem']],
            'idrf' => ['eyebrow' => 'Koneksi', 'title' => 'IDRF', 'subtitle' => 'Koneksi ke ekosistem Indonesia Development Research Forum.', 'body' => 'IDRF menghubungkan kerja riset, pembangunan, pembelajaran, dan pengetahuan untuk memperkuat basis data serta argumentasi kebijakan.', 'image_path' => '/assets/img/cea/campur.png', 'cards' => ['Riset', 'Pembangunan', 'Pengetahuan', 'Kebijakan']],
            'simpul-pfb' => ['eyebrow' => 'Koneksi', 'title' => 'Simpul PFB', 'subtitle' => 'Kanal simpul dan jejaring pendukung berbasis wilayah.', 'body' => 'Simpul PFB disiapkan sebagai kanal koneksi untuk memperkuat koordinasi, pertukaran informasi, dan jejaring pendukung berbasis wilayah.', 'image_path' => '/assets/img/cea/campur.png', 'cards' => ['Simpul', 'Wilayah', 'Koordinasi', 'Jejaring']],
            'baku-dapa' => ['eyebrow' => 'Koneksi', 'title' => 'Baku-Dapa', 'subtitle' => 'Ruang siar, radio komunitas, dan koneksi narasi bersama.', 'body' => 'Baku-Dapa memperkuat kerja narasi, ruang dengar, dan kanal komunikasi komunitas dalam ekosistem gerakan.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%285%29.png', 'cards' => ['Radio Komunitas', 'Ruang Siar', 'Narasi', 'Komunitas']],
            'telisik' => ['eyebrow' => 'Koneksi', 'title' => 'Telisik', 'subtitle' => 'Kanal observasi, pembacaan isu, dan penelusuran data.', 'body' => 'Telisik menjadi kanal untuk mengamati dinamika isu, membaca data, dan menyusun pengetahuan awal bagi advokasi serta respons gerakan.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%286%29.png', 'cards' => ['Observasi', 'Data', 'Isu', 'Analisis']],
            'sociopath' => ['eyebrow' => 'Koneksi', 'title' => 'Sociopath', 'subtitle' => 'Platform sosial dan kanal kolaborasi ekosistem gerakan.', 'body' => 'Sociopath menjadi kanal koneksi sosial untuk memperluas jejaring, kolaborasi, dan pertukaran praktik dalam ekosistem gerakan.', 'image_path' => '/assets/img/cea/pomelli_bdna_image_0510%20%287%29.png', 'cards' => ['Platform Sosial', 'Kolaborasi', 'Jejaring', 'Praktik']],
            'sake-mite' => ['eyebrow' => 'Koneksi', 'title' => 'Sake-Mite', 'subtitle' => 'Kanal koneksi komunitas dan pertukaran praktik baik.', 'body' => 'Sake-Mite disiapkan sebagai ruang koneksi komunitas untuk saling bertukar praktik, pengalaman, dan pembelajaran antaraktor lokal.', 'image_path' => '/assets/img/cea/campur.png', 'cards' => ['Komunitas', 'Praktik Baik', 'Pertukaran', 'Pembelajaran']],
            'civil-colony' => ['eyebrow' => 'Koneksi', 'title' => 'Civil Colony', 'subtitle' => 'Ruang kolektif untuk koneksi masyarakat sipil.', 'body' => 'Civil Colony menjadi ruang kolektif untuk mempertemukan gagasan, kerja, dan koneksi masyarakat sipil lintas wilayah serta lintas isu.', 'image_path' => '/assets/img/cea/campur.png', 'cards' => ['Ruang Kolektif', 'Masyarakat Sipil', 'Gagasan', 'Koneksi']],
        ],
        'kolektif' => [
            '_section' => ['eyebrow' => 'Kolektif', 'title' => 'Kolektif', 'subtitle' => 'Narasi kolektif, testimoni simpul, dan arsip kolaborasi.', 'body' => 'Kolektif menjadi ruang untuk menghimpun cerita, testimoni, refleksi, dan arsip kolaborasi dari simpul, anggota, serta mitra Pooling Fund - KSO.', 'image_path' => '/assets/img/cea/campur.png', 'cards' => ['Narasi', 'Testimoni', 'Arsip', 'Kolaborasi']],
        ],
    ],
];
